version: "3"
services:
  develop:
    build: .
    ports:
      - "30540:3100"
    container_name: gfw-user-api-develop
    environment:
      PORT: 3100
      MIGRATE_URI: <urlmigrate>
      NODE_PATH: app/src
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      MONGO_PORT_27017_TCP_ADDR: gfw-user-mongo-develop
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      REQUIRE_API_KEY: "false"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "false"
      GATEWAY_URL: "http://host.docker.internal:4566/_aws/execute-api/l0xikwwhja/prod"
    command: start
    links:
      - mongo
    volumes:
      - ./app:/opt/gfw-user-api/app

  mongo:
    image: mongo:3.6
    container_name: gfw-user-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/dataset:/data/db
    restart: always
