apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: gfw-user
    app: gfw
  name: gfw-user
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: gfw-user
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gfw"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - gfw
      containers:
      - name: gfw-user
        image: vizzuality/gfw-user
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "3100"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://gfw-user.gfw.svc.cluster.local:3100
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: USER_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 3100

      restartPolicy: Always
