swagger: '2.0'
###############################################################################
#                              API Information                                 
###############################################################################
info:
  title: GLobal Forest Watch API
  description: |
    The Global Forest Watch API is currently in beta. Based on feedback from trusted testers, this document specifies new API changes that are currently under development. Interested in being a trusted tester? Contact the [Data Lab](mailTo:support@wri.com) at World Resources Institute.
    
    All endpoints are accessible via http & https and are located at
    `https://production-api.globalforestwatch.org`.
    
    Forest change measures tree cover loss, tree cover gain, or forest disturbance. The following forest change data are available through the API: 
    * University of Maryland tree cover loss & gain 
    * FORMA alerts
    * IMAZON SAD alerts
    * Terrai alerts
    * Prodes
    * Guira Loss
    * Biomass loss
    * GLAD tree cover loss alerts 
    * NASA VIIRs active fires.
    
    Other services provided by the Api complements the ecosystem that surrounds the platform:
    
    * Metadata
    * Urthecast 
    * Geostore
    * OGR 
    * Story 
    * User 
    * subscription
    
  
    ### User API
    This Microservice will provide a comprehensive way of create, modify or delete users within the platform
    
    
  termsOfService: http://www.globalforestwatch.org/terms
  contact:
    name: API Support
    url: http://www.globalforestwatch.org
    email: support@wri.com
  license:
    name: MIT License (MIT)
    url: https://opensource.org/licenses/MIT
  version: "1.0.0"
  
host: staging-api.globalforestwatch.org

schemes:
  - https
  - http

consumes:
  - application/vnd.api+json

produces:
  - application/vnd.api+json
###############################################################################
#                                  Security                                    
###############################################################################
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: Authorization
    description: |
     For write operations it's need an api key like  ```Bearer {{TOKEN}}```.
     
     To obtain it please contact [support](mailto:support@wri.com).
###############################################################################
#                                  Paths                                   
###############################################################################
paths:
  /user/{id}:
    delete:
      description: |
        Delete user based on a single ID, if the user not exist return 404
        **Is necesary authentication**
        #### Example response
        ```json
        {
            "data": {
                "type": "user",
                "id": "516a333ba0008d0e003b733b",
                "attributes": {
                    "provider": "twitter",
                    "providerId": "000000000",
                    "email": "vizz@vizzuality.com",
                    "createdAt": "2016-06-23T15:41:41.248Z",
                    "primaryResponsibilities": ["responsabilities"],
                    "howDoYouUse": ["testing"],
                    "signUpForTesting": false,
                    "country": "Spain",
                    "city": "Madrid",
                    "stage": ""
                }
            }
        }
        ```
      operationId: deleteUserById
      produces:
        - application/vnd.api+json
      tags:
        - USER
      parameters:
        - name: id
          in: path
          description: ID of user to delete
          required: true
          type: string
      security:
        - UserSecurity: []
      responses:
        200:
          description: User deleted
          schema:
            $ref: '#/definitions/UserAPI'
        401:
          description: Not authorized. if you try to delete a different user to yours
          schema:
            $ref: '#/definitions/Errors'
        404:
          description: User not found
          schema:
            $ref: '#/definitions/Errors'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Errors'
    put:
      summary: Update user
      description: |
        Update user based on a single ID, if the user not exist return 404
        **Is necesary authentication**
        #### Example response
        ```json
        {
            "data": {
                "type": "user",
                "id": "516a333ba0008d0e003b733b",
                "attributes": {
                    "provider": "twitter",
                    "providerId": "000000000",
                    "email": "vizz@vizzuality.com",
                    "createdAt": "2016-06-23T15:41:41.248Z",
                    "primaryResponsibilities": ["responsabilities"],
                    "howDoYouUse": ["testing"],
                    "signUpForTesting": false,
                    "country": "Spain",
                    "city": "Madrid",
                    "stage": ""
                }
            }
        }
        ```
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/vnd.api+json
      tags:
        - USER
      parameters:
        - name: id
          in: path
          description: ID of user to update
          required: true
          type: string
        - name: user
          in: body
          description: |
            User to save
            #### Body example
            ```json
            {
                "provider": "twitter",
                "providerId": "000000000",
                "email": "vizz@vizzuality.com",
                "createdAt": "2016-06-23T15:41:41.248Z",
                "primaryResponsibilities": ["responsabilities"],
                "howDoYouUse": ["testing"],
                "signUpForTesting": false,
                "country": "Spain",
                "city": "Madrid",
                "stage": ""
            }
            ```
          required: true
          schema:
            $ref: '#/definitions/UserCreate'
      security:
        - UserSecurity: []
      responses:
        200:
          description: User updated
          schema:
            $ref: '#/definitions/UserAPI'
        401:
          description: Not authorized. if you try to update a different user to yours
          schema:
            $ref: '#/definitions/Errors'
        404:
          description: User not found
          schema:
            $ref: '#/definitions/Errors'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Errors'
  /user:
    post:
      summary: Create user. If user exist, return 400
      description: |
        Create user
        **Is necesary authentication**
        ```json
        {
            "data": {
                "type": "user",
                "id": "516a333ba0008d0e003b733b",
                "attributes": {
                    "provider": "twitter",
                    "providerId": "000000000",
                    "email": "vizz@vizzuality.com",
                    "createdAt": "2016-06-23T15:41:41.248Z",
                    "primaryResponsibilities": ["responsabilities"],
                    "howDoYouUse": ["testing"],
                    "signUpForTesting": false,
                    "country": "Spain",
                    "city": "Madrid",
                    "stage": ""
                }
            }
        }
        ```
      consumes:
        - application/json
      produces:
        - application/vnd.api+json
      tags:
        - USER
      operationId: createUser
      parameters:
        - name: user
          in: body
          description: |
            User to save
            #### Body example
            ```json
            {
                "provider": "twitter",
                "providerId": "000000000",
                "email": "vizz@vizzuality.com",
                "createdAt": "2016-06-23T15:41:41.248Z",
                "primaryResponsibilities": ["responsabilities"],
                "howDoYouUse": ["testing"],
                "signUpForTesting": false,
                "country": "Spain",
                "city": "Madrid",
                "stage": ""
            }
            ```
          required: true
          schema:
            $ref: '#/definitions/UserCreate'
      security:
        - UserSecurity: []
      responses:
        200:
          description: The user created
          schema:
            $ref: '#/definitions/UserAPI'
        400:
          description: Validate error or duplicated user
          schema:
            $ref: '#/definitions/Errors'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'


definitions:
  Errors:
    type: object
    description: Errors
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'

  Error:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: A unique identifier for this particular occurrence of the problem.
      links:
        type: object
        description: A links object
        properties:
          about:
            type: string
            description: A link that leads to further details about this particular occurrence of the problem.
      status:
        type: string
        description: The HTTP status code applicable to this problem, expressed as a string value
      code:
        type: string
        description: An application-specific error code, expressed as a string value
      title:
        type: string
        description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
      detail:
        type: string
        description: A human-readable explanation specific to this occurrence of the problem. Like title, this field's value can be localized
      source:
        type: object
        description: An object containing references to the source of the error, optionally including any of the following members
        properties:
          pointer:
            type: string
            description: A JSON Pointer [RFC6901] to the associated entity in the request document
          parameter:
            type: string
            description: A string indicating which URI query parameter caused the error.
      meta:
        type: object
        description: A meta object containing non-standard meta-information about the error.


  UserAPI:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/User'

  User:
    type: object
    properties:
      type:
        type: string
        description: Resource type
      id:
        type: string
        description: Resource id
      attributes:
        properties:
          schema:
            $ref: '#/definitions/UserData'
  UserData:
    type: object
    properties:
      fullName:
        type: string
      provider:
        type: string
        description: Provider of oauth
      providerId:
        type: string
        description: Id of provider obtained in the authentication
      email:
        type: string
      createdAt:
        type: string
      sector:
        type: string
      primaryResponsabilities:
        type: string
      country:
        type: string
      state:
        type: string
      city:
        type: string
      howDoYouUse:
        type: string

  UserCreate:
    allOf:
      - $ref: '#/definitions/UserData'
    type: object
